// Code generated by github.com/wylswz/cue-se/pkg/gen. DO NOT EDIT.

package ed25519

import (
	"github.com/wylswz/cue-se/internal/core/adt"
	"github.com/wylswz/cue-se/internal/pkg"
)

func init() {
	pkg.Register("crypto/ed25519", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{{
		Name:  "PublicKeySize",
		Const: "32",
	}, {
		Name: "Valid",
		Params: []pkg.Param{
			{Kind: adt.BytesKind | adt.StringKind},
			{Kind: adt.BytesKind | adt.StringKind},
			{Kind: adt.BytesKind | adt.StringKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			publicKey, message, signature := c.Bytes(0), c.Bytes(1), c.Bytes(2)
			if c.Do() {
				c.Ret, c.Err = Valid(publicKey, message, signature)
			}
		},
	}},
}
