// Code generated by gocode.Generate; DO NOT EDIT.

package pkg2

import (
	"fmt"

	"github.com/wylswz/cue-se/cue"
	"github.com/wylswz/cue-se/encoding/gocode/gocodec"
	_ "github.com/wylswz/cue-se/pkg"
)

var cuegenvalImportMe = cuegenMake("ImportMe", &ImportMe{})

// Validate validates x.
func (x *ImportMe) Validate() error {
	return cuegenCodec.Validate(cuegenvalImportMe, x)
}

var cuegenvalPickMe = cuegenMake("PickMe", nil)

// Validate validates x.
func (x PickMe) Validate() error {
	return cuegenCodec.Validate(cuegenvalPickMe, x)
}

var cuegenCodec, cuegenInstance_, cuegenValue = func() (*gocodec.Codec, *cue.Instance, cue.Value) {
	var r *cue.Runtime
	r = &cue.Runtime{}
	instances, err := r.Unmarshal(cuegenInstanceData)
	if err != nil {
		panic(err)
	}
	if len(instances) != 1 {
		panic("expected encoding of exactly one instance")
	}
	return gocodec.New(r, nil), instances[0], instances[0].Value()
}()

// Deprecated: cue.Instance is deprecated. Use cuegenValue instead.
var cuegenInstance = cuegenInstance_

// cuegenMake is called in the init phase to initialize CUE values for
// validation functions.
func cuegenMake(name string, x interface{}) cue.Value {
	f, err := cuegenValue.FieldByName(name, true)
	if err != nil {
		panic(fmt.Errorf("could not find type %q in instance", name))
	}
	v := f.Value
	if x != nil {
		w, err := cuegenCodec.ExtractType(x)
		if err != nil {
			panic(err)
		}
		v = v.Unify(w)
	}
	return v
}

// Data size: 288 bytes.
var cuegenInstanceData = []byte("\x01\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xffD\xcf\xc1J31\x10\a\xf0\xf9o\xf7\x83\xaf\xa1\n>\x80\xb0\xec\xa9\x1e\xdcT\xc1\x1e\x8a\bU\x11<(\u016bxH\u04f8\rm\x93\xa5\xc9R\xaa\x88Z\xab\xcf\xe4\xdbER*\x9e\x06~3\xffaf'|&H\xc2\x17!\xbc\x11u_\x1b@K\x1b\u7151\xeaRx\x11\x19\r\xa4w\xd6z$\x84t \xfc\x18-\u00bf+=U\x0eaMD\xfb\xe1#\x01v\xef\x1fd\xad\x8aG=\xdd&\u05c4\xb0\"j\x87\xf7\x06\xf0\xff\xcfW\x84\x04\u9b58\xa9\xb8(\xdd #\xa2\xf0\x1d\xef\x00\xd0-\xb5\x1f\xd7\xc3B\xda\x19_,\xa7n\xf1\xc4e\xad\x0e\x9d\xe2\xcaH;\u04a6\u4955v\xa4\xb8W\u038f\x84\x17\xbc\x9a\x94\xc7\x00\xf6b\xe5\xbf\x0f\x14\xb2V\x10\x95\x90\x13Q\xaa,\xb6\x18\u04f3\xca\xce}\x96;?\u05e6t9c\xd7\x1b\xb9Q\xbd\xec\x995\xfb\xbd\xec\xf4\xa8\xd3a\xcd\xf3^\xb6\x1d).\xac\xf1B\x1b\xd77\xcbv.\x862?`/l\xa0\xe5$f\xceN\x18\xd1O\x00\x00\x00\xff\xffq\xb6\xe1\x06F\x01\x00\x00")
