// Code generated by gocode.Generate; DO NOT EDIT.

package pkg1

import (
	"fmt"

	"github.com/wylswz/cue-se/cue"
	"github.com/wylswz/cue-se/encoding/gocode/gocodec"
	_ "github.com/wylswz/cue-se/pkg"
)

var cuegenvalMyStruct = cuegenMake("MyStruct", &MyStruct{})

// Validate validates x.
func (x *MyStruct) Validate() error {
	return cuegenCodec.Validate(cuegenvalMyStruct, x)
}

// Complete completes x.
func (x *MyStruct) Complete() error {
	return cuegenCodec.Complete(cuegenvalMyStruct, x)
}

var cuegenvalOtherStruct = cuegenMake("OtherStruct", &OtherStruct{})

// Validate validates x.
func (x *OtherStruct) Validate() error {
	return cuegenCodec.Validate(cuegenvalOtherStruct, x)
}

var cuegenvalString = cuegenMake("String", nil)

// ValidateCUE validates x.
func (x String) ValidateCUE() error {
	return cuegenCodec.Validate(cuegenvalString, x)
}

var cuegenvalSpecialString = cuegenMake("SpecialString", nil)

// ValidateSpecialString validates x.
func ValidateSpecialString(x string) error {
	return cuegenCodec.Validate(cuegenvalSpecialString, x)
}

var cuegenvalPtr = cuegenMake("Ptr", Ptr(nil))

// ValidatePtr validates x.
func ValidatePtr(x Ptr) error {
	return cuegenCodec.Validate(cuegenvalPtr, x)
}

var cuegenCodec, cuegenInstance_, cuegenValue = func() (*gocodec.Codec, *cue.Instance, cue.Value) {
	var r *cue.Runtime
	r = &cue.Runtime{}
	instances, err := r.Unmarshal(cuegenInstanceData)
	if err != nil {
		panic(err)
	}
	if len(instances) != 1 {
		panic("expected encoding of exactly one instance")
	}
	return gocodec.New(r, nil), instances[0], instances[0].Value()
}()

// Deprecated: cue.Instance is deprecated. Use cuegenValue instead.
var cuegenInstance = cuegenInstance_

// cuegenMake is called in the init phase to initialize CUE values for
// validation functions.
func cuegenMake(name string, x interface{}) cue.Value {
	f, err := cuegenValue.FieldByName(name, true)
	if err != nil {
		panic(fmt.Errorf("could not find type %q in instance", name))
	}
	v := f.Value
	if x != nil {
		w, err := cuegenCodec.ExtractType(x)
		if err != nil {
			panic(err)
		}
		v = v.Unify(w)
	}
	return v
}

// Data size: 611 bytes.
var cuegenInstanceData = []byte("\x01\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xff\x9cR\xc1n\xdb8\x10%e/\xb0&\xb2\v\xec\a,0\u02d3\xbd\xd8H\xb6\x81\xcdA\x88\xda&iZ\xe4\x90\xd8h\u06a2@\xd1\x03-\x8de\"4\xa9\x9aT\x12\xb7M\u06a6i>;*$K\x89\xdbct\xd1`\xc87\xef\xcd\xe3\xfb\xa3\xf8\xeeQ\xaf\xb8!\xb4\xf8B\xc8\xd6\xe7\x16\xa5\x1bR['t\x8cO\x85\x13e\x9b\xb6h\xfb\x851\x8ez\x84\xb6\xc7\xc2\xcd\xe8\x06\xa1\xbf=\x93\n--\xae\t!\x7f\x17\xdf<J\xff|\xfb.\xce\u045fJU#\xaf\t-\xae\b\xe9\x16_[\x94\xfe~\u07ff\"\u0523\xed#1\xc7rP\xbbj2B\xc8m\xcb\x147\u0123\x94n\xa5\xd2\xcd\xf2\x89\x1f\x9byp\xb6T\xf6\xecC\x10\xe7\xb8i1@\x1d\x9bD\xea4HMl\x12\f\x1cZ\x97\b'\x82\xec$\x1dPJ\xff*\xffA\xb3\x81\x1f\xe7Ho\xbd$\x13\xf1\x89H\x11\xcaC\xc6\xe4<3\v\a]\xd6\xe1\x0f\xe2\x19r\xd6\xe1\xd6-\xa4NmY\u0385\x9bq\xd6c\xecpy\xec\x16y\xecB\xf8\xc8:;!\xc0v4\xe8\xb3\xcen\b\x10]\xf2X8\x0e\x9f\xe0_\x9e\x98\x94\xb3\xce\xe8q\b#7\xc3\xc5\n\xc3:\a!\x94\x02\x87\xfeA\xa5\xef\x10\xd9\x05<IM\xf7\xbf\xd8\xcc3\x85\x0e\xa3\xbd\xba\xe8\xb15`CV\v\xf2\xf7\x8cvBj\xbb\xa3\x97]\xfe\x86\xf7Xg\x1c\xae\xe6\x8ee|RNe\xc7\xd5\xd5\x10\xea\uf7c8\xf3\xa6\xae\bO\x85\x92\x89p\x18\xbd\xae\x8b\xbdW\xfb=v\x9ca,\x85j\xc0\xd1%\xb7\xab\x0e_\xa1\xdc2\xc3h\xa5\xa2\xc7\x0eRm\x16\xf8r&mE\x13]\xf2\xa91\x9c\x8d\xe6\xd2\xdd\xf1\x02H\xed*\xecf\x8f\xb1 \x80#\xa3\xf7\u03e5uR\xa7p&\x95\x82\t\x82\x99K\xe70\x01a\xa1\xdc\x19AZ\xd0\x06\xf0}.O\x85B\xed\u0e41\x92\xdagk\xf0\u0294\xdd\u0194\xda\u021aEV\xd2 \xd7x^\xfa\x8c\t\xe4Z\xa1\xb5\x80\u7652\xb1tj\t\xa8\xc5Da\u2ce91a)\x93\x8d\u0762q\xba|o\xff0WNf\nG\xd3\xee\xa0\xdfc\x17\x8c\x10\xefa\xb1\x1d\u05b1\x1d\xfe\x1c[\xb1\x16\xda\xe1]h\xefs\u01da\x984\xb2\xb6\a\xfd\xfe\xda\u04bf$ALb^\xca\\\x85 \x84G\xff3B~\x04\x00\x00\xff\xff\u0593\xb3N\xfe\x03\x00\x00")
