// Code generated by github.com/wylswz/cue-se/pkg/gen. DO NOT EDIT.

package uuidx

import (
	"github.com/wylswz/cue-se/internal/core/adt"
	"github.com/wylswz/cue-se/internal/pkg"
)

func init() {
	pkg.Register("uuidx", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{{
		Name:   "UUID",
		Params: []pkg.Param{},
		Result: adt.StringKind,
		Func: func(c *pkg.CallCtxt) {
			if c.Do() {
				c.Ret = UUID()
			}
		},
	}},
}
