// Code generated by github.com/wylswz/cue-se/pkg/gen. DO NOT EDIT.

package httpx

import (
	"github.com/wylswz/cue-se/internal/core/adt"
	"github.com/wylswz/cue-se/internal/pkg"
)

func init() {
	pkg.Register("httpx", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{{
		Name: "JsonGet",
		Params: []pkg.Param{
			{Kind: adt.StringKind},
			{Kind: adt.TopKind},
			{Kind: adt.TopKind},
		},
		Result: adt.TopKind,
		Func: func(c *pkg.CallCtxt) {
			urlStr, parameters, headers := c.String(0), c.Value(1), c.Value(2)
			if c.Do() {
				c.Ret, c.Err = JsonGet(urlStr, parameters, headers)
			}
		},
	}},
}
