// Code generated by github.com/wylswz/cue-se/pkg/gen. DO NOT EDIT.

package timex

import (
	"github.com/wylswz/cue-se/internal/core/adt"
	"github.com/wylswz/cue-se/internal/pkg"
)

func init() {
	pkg.Register("timex", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{{
		Name:   "CurrentUnixMillis",
		Params: []pkg.Param{},
		Result: adt.IntKind,
		Func: func(c *pkg.CallCtxt) {
			if c.Do() {
				c.Ret = CurrentUnixMillis()
			}
		},
	}, {
		Name:   "CurrentUnixNanos",
		Params: []pkg.Param{},
		Result: adt.IntKind,
		Func: func(c *pkg.CallCtxt) {
			if c.Do() {
				c.Ret = CurrentUnixNanos()
			}
		},
	}},
}
